import java.sql.*;
import Project.ConnectionProvider;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maya samdade
 */


public class Billing extends javax.swing.JFrame {
    
public int finaltotal=0;
public int billno;

    /**
     * Creates new form Billing
     */
    public Billing() throws SQLException {
        
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date =new Date();
        jLabel5.setText(dFormat.format(date));
        
        DateTimeFormatter dtf= DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now =LocalDateTime.now();
       
        jLabel6.setText(dtf.format(now));
        
       
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(bid) FROM bill");

            if (rs.next()) {
                int id = rs.getInt(1);
                id = id + 1;
                billno = id;
            } else {
               System.out.println("Somthing Went Wrong in Bill No.");
            }

    // Close resources in reverse order of creation
        rs.close();
        st.close();
        con.close();
       
        
         /**/
        
        /**/
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fbilling.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Billing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 290, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1570, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Details:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 199, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 198, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 198, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 198, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventary Details:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mobile Brand");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Category");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 570, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Rate");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Description");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 540, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 450, 180, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 570, 180, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 490, 180, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 530, 180, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quantity");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 610, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 610, 180, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newadd.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 650, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID","Mobile Brand", "Category", "Rate", "Description", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 820, 990, 140));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Calculation Details:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 710, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 770, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Paid Amount");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 810, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Return Amount");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 850, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 760, 150, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 800, 150, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 840, 152, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Inventary Id");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 380, -1, -1));

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 380, 178, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newsave.png"))); // NOI18N
        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 910, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newreset.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 910, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newclose.png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 910, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Device Details:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("DeviceID");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DeviceType");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, 27));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Brand");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Model");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("IMEI");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Repair History");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Device Condition");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Date Received");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Notes");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, -1, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 140, -1));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 140, -1));

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 140, -1));

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 140, -1));

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 190, -1));

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 140, -1));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 140, -1));

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 140, -1));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 140, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newadd.png"))); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 110, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DeviceID", "DeviceType", "Brand", "Model", "IMEISerialNumber", "RepairHistory", " DeviceCondition", "DateReceived", "Notes", "CustomerContactNo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 990, 130));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mobile No");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 140, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 624, 1490, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, 1560, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 890, 470, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 694, 560, 10));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 20, 110));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newsearch.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1058, 371, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from customer where name like '"+name+"%'");
            if(rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
            }
            else
            {
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
                String contactNo=jTextField2.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from customer where contactNo like '"+contactNo+"%'");
            if(rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
            }
            else
            {
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }
            
            
           /*DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
            //model.addRow(new Object[]{});
            rs=st.executeQuery("select * from Fdevice where CustomerContactNo ="+contactNo+"");
            while(rs.next())
               {model.addRow(new Object[]{
                   rs.getString(1),
                   rs.getString(2),
                   rs.getString(3),
                   rs.getString(4),
                   rs.getString(5),
                   rs.getString(6),
                   rs.getString(7),
                   rs.getString(8),
                   rs.getString(9),
                   rs.getString(10)});
                   
} */
            
        }
        
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    try {
        new Billing().setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
        String id=jTextField13.getText();
        try
            {
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
               ResultSet rs=st.executeQuery("select * from inventary where iId='"+id+"'");
               if(rs.next())
               {
                   jTextField5.setText(rs.getString(2));
                   jTextField6.setText(rs.getString(3));
                   jTextField7.setText(rs.getString(4));
                   jTextField8.setText(rs.getString(5));
                   jTextField9.setText("1");
                   
               }
               else
                   JOptionPane.showMessageDialog(null,"Inventary Id does not Exist");
            }
            catch(Exception e)
            {
               
            }
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int price=Integer.parseInt(jTextField7.getText());
        int quantity=Integer.parseInt(jTextField9.getText());
        int total=price*quantity;
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{jTextField13.getText(),jTextField5.getText(),jTextField6.getText(),price,jTextField8.getText(),quantity,total});
        finaltotal = finaltotal + total;
        String finalTotal1=String.valueOf(finaltotal);
        jTextField10.setText(finalTotal1);
        
        
        
        
        
        //agranis code
        
        
         System.out.println("BillNo :- "+billno+"   \t Row:- "+jTable1.getRowCount());
           try{
           //for(int i=1;i<=jTable1.getRowCount();i++){
               
               //BigInteger uphno = new BigInteger(jTextField2.getText());
               String uphno = jTextField2.getText();
               int inventory_id = Integer.parseInt(jTextField13.getText());
               int device_id = Integer.parseInt(jTextField14.getText());
               String uname = jTextField1.getText(); 
               String category = jTextField6.getText();
               String repairHST = jTextField19.getText();
               int quantityused = Integer.parseInt(jTextField9.getText());
               int rate = Integer.parseInt(jTextField7.getText());
               System.out.println("\t Inventory Id= "+inventory_id);
               /*System.out.print("phoneno:- "+uphno +"Billno:- "+ billno +"Inventory id:-"+ inventory_id +"Device Id:-"+ device_id +"Name:- "+ uname +"Category:-" + category +"Repair History:- "+ repairHST +"Quantity :-"+ quantityused+ "Rate:- "+ rate);          */
                String Query="Insert into bill value("+uphno+","+billno+","+inventory_id +","+ device_id +",'"+ uname +"','"+category +"','"+repairHST+"',"+quantityused+","+rate+",Current_date());";
               
               //System.out.println("\n QUERY "+Query);
               
               
              
    Connection con = ConnectionProvider.getCon();
    Statement st = con.createStatement();
    st.executeUpdate(Query);
  }
           catch(NumberFormatException | SQLException  aar){System.out.println(" Error in Pst Message:-  "+aar.getMessage());}
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        String paidamt=jTextField11.getText();
        int z=Integer.parseInt(paidamt
        );
        finaltotal = z-finaltotal;
        String finalTotal1=String.valueOf(finaltotal);
        jTextField12.setText(finalTotal1);
        jTextField12.setEditable(false);
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      /* try{
          Connection con=ConnectionProvider.getCon();
          
          int ustock = Integer.parseInt(jTextField9.getText());
          int iid = Integer.parseInt(jTextField13.getText());
          System.out.println("IId :- "+ iid + " Used Stock :- "+ustock);
          Statement st=con.createStatement();
          //System.out.print("- - 1- -");
          String s ="select iid,remainingstock,soldstock from inventary where iid="+iid;
          
          //System.out.println(s+" - - 2i - - ");
          ResultSet r = st.executeQuery(s);
          //System.out.print("- - 2- - ");
          int remainingStock =0 ,soldStock=0;
          while(r.next()){
          remainingStock = Integer.parseInt(r.getString(2));
          //System.out.print("- - 3- -");
          soldStock = Integer.parseInt(r.getString(3));
          System.out.println("OLD -----  Remaining Stock :- "+ remainingStock + " Sold Stock :- "+soldStock);
          }
          if (remainingStock == 0){
              JOptionPane.showMessageDialog(null,"Stock is Zero.");
              
          }else{
          System.out.print("- - 4- -");
          int newRemainingStock = remainingStock - ustock;
          int newSoldStock = ustock + soldStock;
          System.out.println("NEW -----  Remaining Stock :- "+ newRemainingStock + " Sold Stock :- "+newSoldStock);
          
          st=con.createStatement();
          st.executeUpdate("UPDATE inventary SET remainingstock ="+newRemainingStock+" , soldstock = "+newSoldStock+" WHERE iid ="+iid+";");}
      
           
        }catch(HeadlessException | NumberFormatException | SQLException n){}*/
      
      
      
      try {
    Connection con = ConnectionProvider.getCon();

    // Assuming your 'jTable' is your JTable
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    for (int i = 0; i < model.getRowCount(); i++) {
        int ustock = Integer.parseInt(model.getValueAt(i, 5/* index of ustock column */).toString());
        int iid = Integer.parseInt(model.getValueAt(i,0 /* index of iid column */).toString());
        
        System.out.println("IId: " + iid + " Used Stock: " + ustock);

        Statement st = con.createStatement();
        String selectQuery = "SELECT remainingstock, soldstock FROM inventary WHERE iid = " + iid;

        ResultSet rs = st.executeQuery(selectQuery);

        int remainingStock = 0, soldStock = 0;

        while (rs.next()) {
            remainingStock = rs.getInt("remainingstock");
            soldStock = rs.getInt("soldstock");
            System.out.println("Old - Remaining Stock: " + remainingStock + " Sold Stock: " + soldStock);
        }

        rs.close();

        if (remainingStock == 0) {
            JOptionPane.showMessageDialog(null, "Stock is Zero.");
        } else {
            int newRemainingStock = remainingStock - ustock;
            int newSoldStock = ustock + soldStock;
            System.out.println("New - Remaining Stock: " + newRemainingStock + " Sold Stock: " + newSoldStock);

            String updateQuery = "UPDATE inventary SET remainingstock = ?, soldstock = ? WHERE iid = ?";
            try (PreparedStatement pst = con.prepareStatement(updateQuery)) {
                pst.setInt(1, newRemainingStock);
                pst.setInt(2, newSoldStock);
                pst.setInt(3, iid);
                pst.executeUpdate();
                System.out.println("Update successful.");
            } catch (SQLException e) {
                System.out.println("Error in PreparedStatement: " + e.getMessage());
            }
        }

        st.close();
    }

    con.close();
} catch (NumberFormatException | SQLException e) {
    System.out.println("Error: " + e.getMessage());
}

      
      
      
            
        
       
       
    // TODO add your handling code here:
        String name=jTextField1.getText();
        String contactNo=jTextField2.getText();
        String email=jTextField3.getText();
        String address=jTextField4.getText();
        String path="C:\\Users\\maya samdade\\OneDrive\\Documents\\NetBeansProjects\\billing system\\Project PDF";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path=""+name+" "+jLabel5.getText()+".pdf"));
            doc.open();
            Paragraph paragraph1=new Paragraph("                                 Mobile Service Center(Billing Management System)\n                                             Contact Number:+(91)7499684854\n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("Date & Time: " + jLabel5.getText() + " " + jLabel6.getText() 
                    +"\nCustomer Details :\nName: " + name + "\nContact No: " + contactNo+ "\nEmail: " + email+ "\nAddress: " + address+"\n\n");
            doc.add(paragraph2);
            PdfPTable tb1 = new PdfPTable(7);
            tb1.addCell("id");
            tb1.addCell("Mobile Brand");
            tb1.addCell("Category");
            tb1.addCell("Description");
            tb1.addCell("Rate");
            tb1.addCell("Quantity");
            tb1.addCell("Sub Total");
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                String id= jTable1.getValueAt(i,0).toString();
                String m= jTable1.getValueAt(i,1).toString();
                String c= jTable1.getValueAt(i,2).toString();
                String r= jTable1.getValueAt(i,3).toString();
                String d= jTable1.getValueAt(i,4).toString();
                String q= jTable1.getValueAt(i,5).toString();
                String s= jTable1.getValueAt(i,6).toString();
               // String n= jTable2.getValueAt(i,0).toString();
               tb1.addCell(id);
               tb1.addCell(m);
               tb1.addCell(c);
               tb1.addCell(d);
               tb1.addCell(r);
               tb1.addCell(q);
               tb1.addCell(s);
            }
            doc.add(tb1);
            
            
            
            Paragraph paragraph3 = new Paragraph("\n\n"); 
            doc.add(paragraph3);

            PdfPTable tb2 = new PdfPTable(9);
            tb2.addCell("DeviceID");
            tb2.addCell("DeviceType");
            tb2.addCell("Brand");
            tb2.addCell("Model");
            tb2.addCell("IMEI No");
            tb2.addCell("RepairHistory");
            tb2.addCell("DeviceCondition");
            tb2.addCell("DateReceived");
            tb2.addCell(" Notes");
            for(int i=0;i<jTable2.getRowCount();i++)
            {
                String m1= jTable2.getValueAt(i,0).toString();
                String c1= jTable2.getValueAt(i,1).toString();
                String r1= jTable2.getValueAt(i,2).toString();
                String d1= jTable2.getValueAt(i,3).toString();
                String q1= jTable2.getValueAt(i,4).toString();
                String s1= jTable2.getValueAt(i,5).toString();
                String d2= jTable2.getValueAt(i,6).toString();
                String d3= jTable2.getValueAt(i,7).toString();
                String n1= jTable2.getValueAt(i,8).toString();
            
               tb2.addCell(m1);
               tb2.addCell(c1);
               tb2.addCell(d1);
               tb2.addCell(r1);
               tb2.addCell(q1);
               tb2.addCell(s1);
               tb2.addCell(d2);
               tb2.addCell(d3);
               tb2.addCell(n1);
            }
            doc.add(tb2);
            
            
            Paragraph paragraph4=new Paragraph("\nTotal : "+jTextField10.getText()+"\nPaid Amount : "+jTextField11.getText()+"\nReturn Amount : "+jTextField12.getText()+"\n\nThank you for Visiting ! Please come Again. \nMobile Service Center");
            
            doc.add(paragraph4);
            JOptionPane.showMessageDialog(null, "Bill Generated");
            setVisible(true);
            new Billing().setVisible(true);
        }
        catch(Exception e)
                {
                 JOptionPane.showMessageDialog(null,e); 
                }
        
        
        
        //chatGpt code



   


/*System.out.println("BillNo :- " + billno + "\t Row:- " + jTable1.getRowCount());
try {
    Connection con = ConnectionProvider.getCon();
    String query = "INSERT INTO bill (uphoneno, bid, iid, did, uname, category, repairhistory, quantityused, rate, billdate) " +
                   "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_DATE())";
    try (PreparedStatement pst = con.prepareStatement(query)) {
        for(int i=0;i<jTable2.getRowCount();i++) {
            String uphno = jTextField2.getText();
            Long uph=new Long(uphno);
            
            int inventory_id = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
            int device_id = Integer.parseInt(jTable2.getValueAt(0, 0).toString());
            String uname = jTextField1.getText();
            String category = jTable1.getValueAt(i, 2).toString();
            String repairHST = jTable2.getValueAt(0, 5).toString();
            int quantityused = Integer.parseInt(jTable1.getValueAt(i, 5).toString());
            int rate = Integer.parseInt(jTable1.getValueAt(i, 3).toString());

            pst.setLong(1, uph);
            pst.setInt(2, billno);
            pst.setInt(3, inventory_id);
            pst.setInt(4, device_id);
            pst.setString(5, uname);
            pst.setString(6, category);
            pst.setString(7, repairHST);
            pst.setInt(8, quantityused);
            pst.setInt(9, rate);

            System.out.println("\t Inventory Id= " + inventory_id);
            System.out.println("\n QUERY " + pst.toString());

            pst.executeUpdate();
        }
    }
} catch (NumberFormatException | SQLException aar) {
    System.out.println("Error in Pst Message: " + aar.getMessage());
}*/



        
        
        
        
        doc.close();
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
       String DeviceID=jTextField14.getText();
        try
            {
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
               ResultSet rs=st.executeQuery("select * from Fdevice where DeviceID='"+DeviceID+"'");
               if(rs.next())
               {
                   jTextField15.setText(rs.getString(2));
                   jTextField16.setText(rs.getString(3));
                   jTextField17.setText(rs.getString(4));
                   jTextField18.setText(rs.getString(5));
                   jTextField19.setText(rs.getString(6));
                   jTextField20.setText(rs.getString(7));
                   jTextField21.setText(rs.getString(8));
                   jTextField22.setText(rs.getString(9));
                   jTextField23.setText(rs.getString(10));
                   
               }
               else
                   JOptionPane.showMessageDialog(null,"Inventary Id does not Exist");
            }
            catch(Exception e)
            {
               
            }
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.addRow(new Object[]{jTextField14.getText(),jTextField15.getText(),jTextField16.getText(),jTextField17.getText(),jTextField18.getText(),jTextField19.getText(),jTextField20.getText(),jTextField21.getText(),jTextField22.getText(),jTextField23.getText(),});
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
        String CustomerContactNo=jTextField23.getText();
        try
            {
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
               ResultSet rs=st.executeQuery("select * from Fdevice where CustomerContactNo='"+CustomerContactNo+"'");
               if(rs.next())
               {
                   jTextField14.setText(rs.getString(1));
                   jTextField15.setText(rs.getString(2));
                   jTextField16.setText(rs.getString(3));
                   jTextField17.setText(rs.getString(4));
                   jTextField18.setText(rs.getString(5));
                   jTextField19.setText(rs.getString(6));
                   jTextField20.setText(rs.getString(7));
                   jTextField21.setText(rs.getString(8));
                   jTextField22.setText(rs.getString(9));
                   jTextField23.setText(rs.getString(10));
                   
               }
               else
                   JOptionPane.showMessageDialog(null,"Inventary Id does not Exist");
            }
            catch(Exception e)
            {
               
            }
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
        
      /*  String IMEISerialNumber=jTextField18.getText();
        try
            {
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
               ResultSet rs=st.executeQuery("select * from Fdevice where IMEISerialNumber='"+IMEISerialNumber+"'");
               if(rs.next())
               {
                   jTextField14.setText(rs.getString(1));
                   jTextField15.setText(rs.getString(2));
                   jTextField16.setText(rs.getString(3));
                   jTextField17.setText(rs.getString(4));
                   jTextField18.setText(rs.getString(5));
                   jTextField19.setText(rs.getString(6));
                   jTextField20.setText(rs.getString(7));
                   jTextField21.setText(rs.getString(8));
                   jTextField22.setText(rs.getString(9));
                   jTextField23.setText(rs.getString(10));
                   
               }
               else
                   JOptionPane.showMessageDialog(null,"Inventary Id does not Exist");
            }
            catch(Exception e)
            {
               
            }
        */
        
        
        
        
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String CustomerContactNo=jTextField23.getText();
        String IMEISerialNumber=jTextField18.getText();
        try
            {
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
               //ResultSet rs=st.executeQuery("select * from Fdevice where CustomerContactNo='"+CustomerContactNo+"' && DeviceID='"+DeviceID+"'");
             String query = "SELECT * FROM fdevice WHERE CustomerContactNo = '" + CustomerContactNo + "' AND IMEISerialNumber = '" + IMEISerialNumber + "'";

               ResultSet rs = st.executeQuery(query);
               
               if (rs.next()) {
                    //jTextField2.setText(rs.getString("name")); // Assuming "name" is a field in the "customer" table
                    jTextField14.setText(rs.getString(1));
                   jTextField15.setText(rs.getString(2));
                   jTextField16.setText(rs.getString(3));
                   jTextField17.setText(rs.getString(4));
                   //jTextField18.setText(rs.getString(5));
                   jTextField19.setText(rs.getString(6));
                   jTextField20.setText(rs.getString(7));
                   jTextField21.setText(rs.getString(8));
                   jTextField22.setText(rs.getString(9));
                   jTextField23.setText(rs.getString(10));
                   
                   
                   
                   /*jTextField14.setText(rs.getString(1));
                   jTextField15.setText(rs.getString(2));
                   jTextField16.setText(rs.getString(3));
                   jTextField17.setText(rs.getString(4));
                   jTextField18.setText(rs.getString(5));
                   jTextField19.setText(rs.getString(6));
                   jTextField20.setText(rs.getString(7));
                   jTextField21.setText(rs.getString(8));
                   jTextField22.setText(rs.getString(9));
                   jTextField23.setText(rs.getString(10));*/
                   
                   
                   
                }
            }
            catch(Exception e)
            {
               
            }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Billing().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
