/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package billingpro;
import Project.ConnectionProvider;
import java.awt.Color;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Agrani
 */
public class SearchFrame extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form SearchFrame
     */
    public SearchFrame(){
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Maya@123"); 
        }catch(ClassNotFoundException h){}
        catch(SQLException g){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_device = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_PreviousBills = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_CustDetails = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer No. ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 364, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newsearch.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Devices");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 290, 40));

        jTable_device.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTable_device.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DeviceID", "DeviceType", "Brand", "Model", "IMEI No.", "Repair History", "Device Condition", "Reg Date", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_device);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 1190, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Previous Bills");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 250, 30));

        jTable_PreviousBills.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTable_PreviousBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Device ID", "User Name", "Category", "Repair History", "Quantity Used", "Rate", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable_PreviousBills);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 1200, 120));

        jTable_CustDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTable_CustDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "PhoneNo", "Email ID", "Address", "Reg. Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_CustDetails);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 1190, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newreset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 820, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newclose.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 820, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1310, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String contactNo=jTextField1.getText();
        try
        {
            // For adding Customer Data
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery("select * from customer where contactno like '"+contactNo+"'");
            DefaultTableModel tblmodel = (DefaultTableModel)jTable_CustDetails.getModel();
            while(rs.next()){
                String a[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                tblmodel.addRow(a);
            }
            // For adding Customer's Device's Data
            st= con.createStatement();
            rs=st.executeQuery("select * from fdevice where CustomerContactNo like '"+contactNo+"'");
            DefaultTableModel tblmodel2 = (DefaultTableModel)jTable_device.getModel();
            while(rs.next()){
                String did = String.valueOf(rs.getInt(1));
                String a[]={did,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                tblmodel2.addRow(a);
            }
            // For adding Customer Previous Bill Data
            st= con.createStatement();
            rs=st.executeQuery("select * from bill where uphoneno like '"+contactNo+"'");
            DefaultTableModel tblmodel3 = (DefaultTableModel)jTable_PreviousBills.getModel();
            int total=0;
            int pbid=0,cbid,count=1;
            if (rs.next() != false) { 
                do{
                    cbid = rs.getInt(2);
                    if(count==1){
                        pbid=cbid;
                        System.out.println(" 1st ");
                    }
                    if(cbid==pbid){
                        String bid = String.valueOf(rs.getInt(2));
                        String did = String.valueOf(rs.getInt(4));
                        String quantityused = String.valueOf(rs.getInt(8));
                        String rate = String.valueOf(rs.getInt(9));
                        //String date = String.valueOf(rs.getInt(10));
                        int qu = rs.getInt(8);
                        int r = rs.getInt(9);
                        total=total+(qu*r);
                        String a[]={bid,did,rs.getString(5),rs.getString(6),rs.getString(7),quantityused,rate,rs.getString(10)};
                        tblmodel3.addRow(a);
                        count=count+1;
                        System.out.println("Inside == PBID = "+pbid+" , C="+cbid);
                       
                    }
                    else if(pbid!=cbid){
                        System.out.println("Finish of bill != ");
                        String totalamnt = String.valueOf(total);
                        String a[]={"Date",rs.getString(10)," "," "," "," TOTAL ",totalamnt};
                        tblmodel3.addRow(a);
                        pbid=cbid;
                        System.out.println(" TOTAL == PBID = "+pbid+" , C="+cbid);
                        total=0;
                    
                
                    if(rs.isLast()){
                        String bid = String.valueOf(rs.getInt(2));
                        String did = String.valueOf(rs.getInt(4));
                        String quantityused = String.valueOf(rs.getInt(8));
                        String rate = String.valueOf(rs.getInt(9));
                        int qu = rs.getInt(8);
                        int r = rs.getInt(9);
                        total=total+(qu*r);
                        String a_lastentry[]={bid,did,rs.getString(5),rs.getString(6),rs.getString(7),quantityused,rate,rs.getString(10)};
                        tblmodel3.addRow(a_lastentry);
                        System.out.println("Last != ");
                        totalamnt = String.valueOf(total);
                        String a1[]={"Date",rs.getString(10)," "," "," "," TOTAL ",totalamnt};
                        tblmodel3.addRow(a1);
                        pbid=cbid;
                        System.out.println("LAST  == PBID = "+pbid+" , C="+cbid);
                    }}
                }while(rs.next());
            }else{
                String a[]={"","","","NO RECORDS","","",""};
                tblmodel3.addRow(a);
            }
            
        }catch(SQLException e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int cnt = jTable_CustDetails.getRowCount(); 
        DefaultTableModel model = (DefaultTableModel)jTable_CustDetails.getModel();
        for(int i=0;i<cnt;i++){
            model.removeRow(0);
        }
        cnt = jTable_device.getRowCount(); 
        model = (DefaultTableModel)jTable_device.getModel();
        for(int i=0;i<cnt;i++){
            model.removeRow(0);
        }
        cnt = jTable_PreviousBills.getRowCount(); 
        model = (DefaultTableModel)jTable_PreviousBills.getModel();
        for(int i=0;i<cnt;i++){
            model.removeRow(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrame().setVisible(true);
        }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_CustDetails;
    private javax.swing.JTable jTable_PreviousBills;
    private javax.swing.JTable jTable_device;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
